"""
Calendar Generator — CreativeOps AI

Generates real calendar artefacts from pipeline milestone events:

  1. ICS file  — downloadable .ics attachment that opens in any calendar app
                 (Google Calendar, Apple Calendar, Outlook, etc.)
  2. Google Calendar deep-links  — one-click "Add to Google Calendar" URLs
                                   for each individual event

The mock calendar block generator in tools/mock_outputs.py is kept unchanged
and still runs to produce the event list.  This module takes that list and
produces real calendar output from it.
"""

import re
import urllib.parse
from datetime import datetime, timedelta, timezone
from typing import Optional

# ── icalendar (optional dependency) ─────────────────────────────────────────
try:
    from icalendar import Calendar, Event, vText
    _ICAL_AVAILABLE = True
except ImportError:
    _ICAL_AVAILABLE = False


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _parse_event_dt(date_str: str, time_str: str) -> Optional[datetime]:
    """Parse an event's date + time strings into a naive datetime (local time)."""
    for fmt in ("%Y-%m-%d %H:%M", "%Y-%m-%d %H:%M:%S"):
        try:
            return datetime.strptime(f"{date_str} {time_str}", fmt)
        except ValueError:
            continue
    # Fallback: date only, default 09:00
    try:
        return datetime.strptime(f"{date_str} 09:00", "%Y-%m-%d %H:%M")
    except ValueError:
        return None


def _slugify(name: str) -> str:
    slug = name.lower().strip()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_-]+", "-", slug)
    return slug.strip("-")[:40]


# ---------------------------------------------------------------------------
# 1. ICS file generation
# ---------------------------------------------------------------------------

def generate_ics(
    events: list[dict],
    project_name: str = "Creative Project",
    organiser_email: str = "hello@creativeops.studio",
) -> str | None:
    """
    Generate an ICS calendar file string from a list of milestone event dicts.

    Each event dict should have:
      date, time, title, description, duration_minutes, location, attendees

    Returns:
        ICS text (str) ready to be written to a .ics file, or
        None if icalendar is not installed.
    """
    if not _ICAL_AVAILABLE:
        return None

    cal = Calendar()
    cal.add("prodid",  "-//CreativeOps AI//creativeops.studio//EN")
    cal.add("version", "2.0")
    cal.add("calscale", "GREGORIAN")
    cal.add("method",  "PUBLISH")
    cal.add("x-wr-calname", vText(project_name))
    cal.add("x-wr-caldesc", vText(f"Milestone schedule for {project_name} — generated by CreativeOps AI"))

    for ev_data in events:
        ev = Event()

        dt_start = _parse_event_dt(
            ev_data.get("date", ""),
            ev_data.get("time", "09:00"),
        )
        if dt_start is None:
            continue

        duration_mins = int(ev_data.get("duration_minutes", 60))
        dt_end = dt_start + timedelta(minutes=duration_mins)

        # Unique ID based on date + title slug
        uid = f"{ev_data.get('date','')}-{_slugify(ev_data.get('title','event'))}@creativeops.studio"

        ev.add("uid",       uid)
        ev.add("summary",   ev_data.get("title", "Meeting"))
        ev.add("dtstart",   dt_start)
        ev.add("dtend",     dt_end)
        ev.add("dtstamp",   datetime.now(tz=timezone.utc))
        ev.add("location",  ev_data.get("location", "Google Meet"))
        ev.add("description", ev_data.get("description", ""))
        ev.add("status",    "CONFIRMED")

        # Organiser
        ev.add("organizer", f"mailto:{organiser_email}")

        # Attendees (generic role labels — no real emails)
        for attendee in ev_data.get("attendees", []):
            ev.add("attendee", f"CN={attendee}:mailto:attendee@creativeops.studio")

        cal.add_component(ev)

    return cal.to_ical().decode("utf-8")


# ---------------------------------------------------------------------------
# 2. Google Calendar deep-links
# ---------------------------------------------------------------------------

_GCAL_BASE = "https://calendar.google.com/calendar/render?action=TEMPLATE"


def make_google_calendar_link(event: dict) -> str:
    """
    Build a Google Calendar "Add Event" deep-link for a single milestone.

    The link opens Google Calendar with the event pre-populated.
    The user just has to click "Save" — no OAuth needed.
    """
    dt_start = _parse_event_dt(
        event.get("date", ""),
        event.get("time", "09:00"),
    )
    if dt_start is None:
        return _GCAL_BASE

    duration_mins = int(event.get("duration_minutes", 60))
    dt_end = dt_start + timedelta(minutes=duration_mins)

    # Google Calendar expects YYYYMMDDTHHmmSS (no timezone = floating)
    fmt = "%Y%m%dT%H%M%S"

    params = {
        "text":     event.get("title", "Meeting"),
        "dates":    f"{dt_start.strftime(fmt)}/{dt_end.strftime(fmt)}",
        "details":  event.get("description", ""),
        "location": event.get("location", "Google Meet"),
    }

    return _GCAL_BASE + "&" + urllib.parse.urlencode(params)


def enrich_events_with_links(events: list[dict]) -> list[dict]:
    """
    Return a copy of the events list with a `google_cal_link` field added
    to each event dict.
    """
    enriched = []
    for ev in events:
        ev_copy = dict(ev)
        ev_copy["google_cal_link"] = make_google_calendar_link(ev)
        enriched.append(ev_copy)
    return enriched
